In [42]:
import numpy as np
import pandas as pd
import math

from fontTools.subset import subset
from scipy.signal import impulse
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [15]:
dataset=pd.read_csv('LR/titanic.csv')
dataset.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [16]:
dataset=dataset[['name','sex','age','pclass','cabin','survived']]
dataset.shape

(1310, 6)

In [17]:
dataset

,name,sex,age,pclass,cabin,survived
0,"Allen, Miss. Elisabeth Walton",female,29.0000,1.0,B5,1.0
1,"Allison, Master. Hudson Trevor",male,0.9167,1.0,C22 C26,1.0
2,"Allison, Miss. Helen Loraine",female,2.0000,1.0,C22 C26,0.0
3,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,C22 C26,0.0
4,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,C22 C26,0.0
...,...,...,...,...,...,...
1305,"Zabour, Miss. Thamine",female,NaN,3.0,NaN,0.0
1306,"Zakarian, Mr. Mapriededer",male,26.5000,3.0,NaN,0.0
1307,"Zakarian, Mr. Ortin",male,27.0000,3.0,NaN,0.0
1308,"Zimmerman, Mr. Leo",male,29.0000,3.0,NaN,0.0
1309,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
dataset.describe()

               age       pclass     survived
count  1046.000000  1309.000000  1309.000000
mean     29.881135     2.294882     0.381971
std      14.413500     0.837836     0.486055
min       0.166700     1.000000     0.000000
25%      21.000000     2.000000     0.000000
50%      28.000000     3.000000     0.000000
75%      39.000000     3.000000     1.000000
max      80.000000     3.000000     1.000000

In [19]:
print(dataset.isna().sum(axis=0))

name           1
sex            1
age          264
pclass         1
cabin       1015
survived       1
dtype: int64

In [23]:
data=dataset.dropna(subset=['name','sex','pclass','survived'])
data

,name,sex,age,pclass,cabin,survived
0,"Allen, Miss. Elisabeth Walton",female,29.0000,1.0,B5,1.0
1,"Allison, Master. Hudson Trevor",male,0.9167,1.0,C22 C26,1.0
2,"Allison, Miss. Helen Loraine",female,2.0000,1.0,C22 C26,0.0
3,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,C22 C26,0.0
4,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,C22 C26,0.0
...,...,...,...,...,...,...
1304,"Zabour, Miss. Hileni",female,14.5000,3.0,NaN,0.0
1305,"Zabour, Miss. Thamine",female,NaN,3.0,NaN,0.0
1306,"Zakarian, Mr. Mapriededer",male,26.5000,3.0,NaN,0.0
1307,"Zakarian, Mr. Ortin",male,27.0000,3.0,NaN,0.0
1308,"Zimmerman, Mr. Leo",male,29.0000,3.0,NaN,0.0

In [24]:
print(data.isna().sum(axis=0))

name           0
sex            0
age          263
pclass         0
cabin       1014
survived       0
dtype: int64

In [25]:
data["sex"] = data["sex"].map({"male":1,"female":0})

data["sex"]

0       0
1       1
2       0
3       1
4       0
       ..
1304    0
1305    0
1306    1
1307    1
1308    1
Name: sex, Length: 1309, dtype: int64

In [35]:
le = LabelEncoder()
data['name'] = le.fit_transform(data['name'])
data['cabin']=le.fit_transform(data['cabin'])

In [36]:
data.head()

   name  sex      age  pclass  cabin  survived
0    21    0  29.0000     1.0     43       1.0
1    23    1   0.9167     1.0     79       1.0
2    24    0   2.0000     1.0     79       0.0
3    25    1  30.0000     1.0     79       0.0
4    26    0  25.0000     1.0     79       0.0

In [37]:
feature=data[['name','sex','age','pclass','cabin']]
target=data['survived']
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
feature = imputer.fit_transform(feature)

In [39]:
feature_train, feature_test, target_train, target_test = train_test_split(feature,target)

In [40]:
model = LogisticRegression()
model.fit(feature_train, target_train)
predictions = model.predict(feature_test)

In [44]:
print(confusion_matrix(target_test,predictions))
print(accuracy_score(target_test,predictions))

[[162  37]
 [ 38  91]]
0.7713414634146342